-- Migration 010: Week 2 Features
-- Date: March 2026
-- Features: Dispute/helpful feedback reactions, lab invite codes for team onboarding

-- ============================================
-- 1. user_feedback_on_analysis — dispute/helpful reactions
-- ============================================

CREATE TABLE IF NOT EXISTS user_feedback_on_analysis (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    draft_id UUID REFERENCES drafts(id) ON DELETE CASCADE NOT NULL,
    feedback_id UUID NOT NULL,
    user_id UUID NOT NULL,
    user_action TEXT NOT NULL CHECK (user_action IN ('helpful', 'dispute')),
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- One reaction per user per feedback item (upsert target)
CREATE UNIQUE INDEX IF NOT EXISTS idx_user_feedback_unique
    ON user_feedback_on_analysis(draft_id, feedback_id, user_id);

CREATE INDEX IF NOT EXISTS idx_user_feedback_draft
    ON user_feedback_on_analysis(draft_id);

COMMENT ON TABLE user_feedback_on_analysis IS
    'Tracks whether users find each reviewer feedback item helpful or incorrect (disputed). Used to suppress repeated false-positive flags.';

-- ============================================
-- 2. lab_invites — project-scoped invite codes for lab onboarding
-- ============================================

CREATE TABLE IF NOT EXISTS lab_invites (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    code TEXT UNIQUE NOT NULL,
    project_id UUID REFERENCES projects(id) ON DELETE CASCADE NOT NULL,
    referrer_user_id UUID NOT NULL,
    lab_name TEXT,
    used_count INT DEFAULT 0,
    is_active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_lab_invites_code ON lab_invites(code);
CREATE INDEX IF NOT EXISTS idx_lab_invites_project ON lab_invites(project_id);

COMMENT ON TABLE lab_invites IS
    'Lab-scoped invite codes generated by PIs/postdocs to bring their whole lab onto Noesis. Tied to a specific project. Code format: 8 alphanumeric chars.';
