-- 022_reviewer_panel_quality_v2.sql
-- Stores structured reviewer issues generated by the quality-v2 reviewer panel.

ALTER TABLE reviewer_panel_outputs
    ADD COLUMN IF NOT EXISTS issues JSONB DEFAULT '[]';

