-- Add project insights columns for cross-paper analysis
-- This enables project-level analysis including research gaps, themes, and patterns

-- ============================================
-- PROJECT INSIGHTS COLUMNS
-- ============================================

-- Add insights storage and status tracking to projects table
ALTER TABLE projects
ADD COLUMN IF NOT EXISTS insights JSONB DEFAULT NULL,
ADD COLUMN IF NOT EXISTS insights_status TEXT DEFAULT 'not_analyzed' CHECK (insights_status IN ('not_analyzed', 'analyzing', 'analyzed', 'failed')),
ADD COLUMN IF NOT EXISTS insights_updated_at TIMESTAMP WITH TIME ZONE DEFAULT NULL;

-- Create index for faster queries on insights status
CREATE INDEX IF NOT EXISTS idx_projects_insights_status ON projects(insights_status);

-- Create index for querying projects with insights
CREATE INDEX IF NOT EXISTS idx_projects_has_insights ON projects((insights IS NOT NULL));

-- Comments for documentation
COMMENT ON COLUMN projects.insights IS 'Cross-paper analysis including research gaps, common themes, methodological patterns, timeline, conflicting findings, and citation patterns. Generated by analyzing all document analyses in the project.';
COMMENT ON COLUMN projects.insights_status IS 'Status of insights analysis: not_analyzed, analyzing, analyzed, or failed';
COMMENT ON COLUMN projects.insights_updated_at IS 'Timestamp when insights were last analyzed';
