"""
Export Service

Provides utilities to export literature reviews to various formats:
- Markdown (.md)
- LaTeX (.tex)
- PDF (.pdf)
"""

import re
from typing import Dict, Any
import subprocess
import tempfile
import os


def export_to_markdown(review_text: str, metadata: Dict[str, Any]) -> str:
    """
    Export review to markdown format.

    Args:
        review_text: The literature review text (already in markdown)
        metadata: Review metadata

    Returns:
        Formatted markdown string with metadata header
    """
    # Add metadata header
    header = f"""---
title: Literature Review
structure: {metadata.get('structure', 'thematic')}
num_documents: {metadata.get('num_documents', 0)}
generated_by: Noesis Research Intelligence Platform
---

"""
    return header + review_text


def export_to_latex(review_text: str, metadata: Dict[str, Any]) -> str:
    """
    Export review to LaTeX format.

    Args:
        review_text: The literature review text in markdown
        metadata: Review metadata

    Returns:
        LaTeX document string
    """
    # Convert markdown to LaTeX-friendly format
    # Replace markdown bold **text** with \textbf{text}
    latex_text = re.sub(r'\*\*(.+?)\*\*', r'\\textbf{\1}', review_text)

    # Replace markdown italic *text* with \textit{text}
    latex_text = re.sub(r'\*(.+?)\*', r'\\textit{\1}', latex_text)

    # Replace markdown headers
    latex_text = re.sub(r'^### (.+)$', r'\\subsubsection{\1}', latex_text, flags=re.MULTILINE)
    latex_text = re.sub(r'^## (.+)$', r'\\subsection{\1}', latex_text, flags=re.MULTILINE)
    latex_text = re.sub(r'^# (.+)$', r'\\section{\1}', latex_text, flags=re.MULTILINE)

    # Build full LaTeX document
    latex_doc = rf"""\documentclass[12pt,a4paper]{{article}}
\usepackage[utf8]{{inputenc}}
\usepackage{{geometry}}
\usepackage{{hyperref}}
\usepackage{{cite}}

\geometry{{margin=1in}}

\title{{Literature Review}}
\author{{Generated by Noesis}}
\date{{\today}}

\begin{{document}}

\maketitle

{latex_text}

\end{{document}}
"""
    return latex_doc


def markdown_to_pdf(markdown_text: str, metadata: Dict[str, Any]) -> bytes:
    """
    Convert markdown to PDF using weasyprint.

    Args:
        markdown_text: The markdown text
        metadata: Review metadata

    Returns:
        PDF file as bytes

    Raises:
        Exception: If PDF generation fails
    """
    try:
        from weasyprint import HTML, CSS
        from markdown import markdown as md_to_html

        # Convert markdown to HTML
        html_content = md_to_html(markdown_text, extensions=['tables', 'fenced_code'])

        # Wrap in HTML document with styling
        full_html = f"""
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <style>
        body {{
            font-family: 'Georgia', serif;
            line-height: 1.6;
            max-width: 800px;
            margin: 40px auto;
            padding: 0 20px;
            color: #333;
        }}
        h1 {{
            color: #2c3e50;
            border-bottom: 3px solid #3498db;
            padding-bottom: 10px;
        }}
        h2 {{
            color: #34495e;
            margin-top: 30px;
            border-bottom: 2px solid #95a5a6;
            padding-bottom: 5px;
        }}
        h3 {{
            color: #7f8c8d;
            margin-top: 20px;
        }}
        p {{
            margin: 15px 0;
            text-align: justify;
        }}
        .metadata {{
            background-color: #ecf0f1;
            padding: 15px;
            border-radius: 5px;
            margin-bottom: 30px;
            font-size: 0.9em;
            color: #7f8c8d;
        }}
    </style>
</head>
<body>
    <div class="metadata">
        <strong>Structure:</strong> {metadata.get('structure', 'N/A').capitalize()} |
        <strong>Documents:</strong> {metadata.get('num_documents', 0)} |
        <strong>Generated by:</strong> Noesis Research Intelligence Platform
    </div>
    {html_content}
</body>
</html>
"""

        # Convert HTML to PDF
        pdf_bytes = HTML(string=full_html).write_pdf()

        return pdf_bytes

    except ImportError:
        # Fallback: If weasyprint is not available, try using pandoc
        return markdown_to_pdf_pandoc(markdown_text, metadata)


def markdown_to_pdf_pandoc(markdown_text: str, metadata: Dict[str, Any]) -> bytes:
    """
    Fallback: Convert markdown to PDF using pandoc.

    Args:
        markdown_text: The markdown text
        metadata: Review metadata

    Returns:
        PDF file as bytes

    Raises:
        Exception: If PDF generation fails
    """
    # Create temporary files
    with tempfile.NamedTemporaryFile(mode='w', suffix='.md', delete=False) as md_file:
        md_file.write(markdown_text)
        md_path = md_file.name

    with tempfile.NamedTemporaryFile(suffix='.pdf', delete=False) as pdf_file:
        pdf_path = pdf_file.name

    try:
        # Use pandoc to convert markdown to PDF
        subprocess.run([
            'pandoc',
            md_path,
            '-o', pdf_path,
            '--pdf-engine=pdflatex',
            '-V', 'geometry:margin=1in'
        ], check=True)

        # Read the generated PDF
        with open(pdf_path, 'rb') as f:
            pdf_bytes = f.read()

        return pdf_bytes

    except subprocess.CalledProcessError as e:
        raise Exception(f"Failed to generate PDF with pandoc: {e}")
    except FileNotFoundError:
        raise Exception("Pandoc is not installed. Please install pandoc or weasyprint for PDF export.")
    finally:
        # Clean up temporary files
        if os.path.exists(md_path):
            os.remove(md_path)
        if os.path.exists(pdf_path):
            os.remove(pdf_path)
